import type { Language } from '../types/i18n'

/** Place tags are data keys (`old-town`); this is how they read in each language. */
const TAGS: Record<string, [vi: string, en: string]> = {
  architecture: ['kiến trúc', 'architecture'],
  'banh-mi': ['bánh mì', 'banh mi'],
  beach: ['bãi biển', 'beach'],
  beef: ['thịt bò', 'beef'],
  birds: ['chim', 'birdlife'],
  boat: ['đi thuyền', 'boat ride'],
  bridge: ['cây cầu', 'bridge'],
  'cable-car': ['cáp treo', 'cable car'],
  cave: ['hang động', 'cave'],
  chinatown: ['phố Hoa', 'Chinatown'],
  clay: ['đồ gốm đất sét', 'clay craft'],
  coffee: ['cà phê', 'coffee'],
  'cooking-class': ['lớp nấu ăn', 'cooking class'],
  crab: ['cua', 'crab'],
  cruise: ['du thuyền', 'cruise'],
  factory: ['xưởng thủ công', 'workshop'],
  farm: ['nông trại', 'farm'],
  'fish-sauce': ['nước mắm', 'fish sauce'],
  garden: ['vườn', 'garden'],
  goat: ['thịt dê', 'goat'],
  heritage: ['di sản', 'heritage'],
  hike: ['đi bộ đường dài', 'hike'],
  history: ['lịch sử', 'history'],
  house: ['nhà cổ', 'old house'],
  island: ['đảo', 'island'],
  karst: ['núi đá vôi', 'karst'],
  lake: ['hồ', 'lake'],
  landmark: ['địa danh', 'landmark'],
  lanterns: ['đèn lồng', 'lanterns'],
  market: ['chợ', 'market'],
  museum: ['bảo tàng', 'museum'],
  'night-market': ['chợ đêm', 'night market'],
  noodles: ['món sợi', 'noodles'],
  'old-town': ['phố cổ', 'old town'],
  park: ['công viên', 'park'],
  pho: ['phở', 'pho'],
  pork: ['thịt heo', 'pork'],
  rice: ['cơm, gạo', 'rice'],
  'rice-field': ['ruộng lúa', 'rice fields'],
  riverfront: ['bờ sông', 'riverfront'],
  rooftop: ['sân thượng', 'rooftop'],
  sculpture: ['điêu khắc', 'sculpture'],
  seafood: ['hải sản', 'seafood'],
  seaside: ['ven biển', 'seaside'],
  shopping: ['mua sắm', 'shopping'],
  skyline: ['toàn cảnh thành phố', 'skyline'],
  'street-food': ['ăn vặt đường phố', 'street food'],
  sunset: ['hoàng hôn', 'sunset'],
  swim: ['bơi lội', 'swimming'],
  tea: ['trà', 'tea'],
  temple: ['đền chùa', 'temple'],
  'thang-co': ['thắng cố', 'thang co'],
  train: ['tàu hỏa', 'train'],
  unesco: ['UNESCO', 'UNESCO'],
  vegetarian: ['món chay', 'vegetarian'],
  view: ['view đẹp', 'great view'],
  viewpoint: ['điểm ngắm cảnh', 'viewpoint'],
  walk: ['đi dạo', 'stroll'],
  waterfall: ['thác nước', 'waterfall'],
}

export function tagLabel(tag: string, language: Language): string {
  const entry = TAGS[tag]
  return entry ? entry[language === 'vi' ? 0 : 1] : tag.replace(/-/g, ' ')
}
